spring:
  datasource:
    url: jdbc:h2:mem:pointdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Table ?? SQL ??? ?? ???? jpa? Batch?? ???? DB ???? ???? ?? none, never?? ???
  # ??? ? ??? jpa??? DB??? ??? Batch??? Schema ??? ??? ?? ?? ??? ?? ??? ?? ????
  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-h2.sql, classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  batch:
    job:
      enabled: false    # ?? job ?? ????  (Spring? ?? ??? ???? job? ??? ??? ???? ?? ?? ???? ??? ????
    jdbc:
      initialize-schema: never    # Batch?? ????? jdbc schema ?? ?? ????(?? ????? ?? ??? ???? ????)

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org,springframework.batch: DEBUG
    com.traffic.pointservicebatch: DEBUG