server:
  port: 8083

spring:
  application:
    name: point-service


  datasource:
    url: jdbc:h2:mem:pointdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

    h2:
      console:
        enabled: true
        path: /h2-console

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}